name: Build & Release

on:
  push:
    branches: [ main ]
    tags:     [ 'v*.*.*' ]
  workflow_dispatch: {}

jobs:
  build:
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Alleen Linux: paar libjes (mag blijven staan; schaadt niet)
      - name: Linux system deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsndfile1-dev libsamplerate0-dev

      # macOS & Linux: bash
      - name: Install deps (numpy first) • macOS/Linux
        if: runner.os != 'Windows'
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install "numpy<2.0"          # aubio 0.4.9 breekt met NumPy 2.x
          pip install -r requirements.txt
          pip install pyinstaller

      # Windows: PowerShell
      - name: Install deps (numpy first) • Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install "numpy<2.0"
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller --onefile --noconsole src/main.py -n ProTuner

      - name: Package artifact
        shell: bash
        run: |
          mkdir -p dist_pkg/assets/branding dist_pkg/assets/screenshots dist_pkg/instruments dist_pkg/presets
          cp -r dist/ProTuner* dist_pkg/
          cp -r assets/branding/* dist_pkg/assets/branding/ || true
          cp -r assets/screenshots/* dist_pkg/assets/screenshots/ || true
          cp -r instruments/* dist_pkg/instruments/ || true
          cp -r presets/* dist_pkg/presets/ || true
          cp version.json CHANGELOG.md README.md LICENSE dist_pkg/
          if [[ "$RUNNER_OS" == "Windows" ]]; then zip -r PRO-tuner-${{ github.ref_name }}-windows.zip dist_pkg; fi
          if [[ "$RUNNER_OS" == "macOS" ]]; then  zip -r PRO-tuner-${{ github.ref_name }}-macos.zip   dist_pkg; fi
          if [[ "$RUNNER_OS" == "Linux" ]]; then   zip -r PRO-tuner-${{ github.ref_name }}-linux.zip   dist_pkg; fi

      - name: Upload artifacts (CI runs)
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: PRO-tuner-${{ matrix.os }}
          path: "*.zip"

      - name: Release (tags only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: "*.zip"
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

